name: github pages

on:
  push:
    paths:
    - pcraster_tools/metadata.txt
    - website/**
    - .github/**

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install mkdocs
        python3 -m pip install MarkdownHighlight
        python3 -m pip install https://codeload.github.com/mkdocs/mkdocs-bootstrap/zip/master

    - name: Build
      run: |
        mkdocs build --config-file ./website/mkdocs.yml
        touch website/docs/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./website/docs
